apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "AhedFinal.fullname" . }}
  labels:
    {{- include "AhedFinal.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cron.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              args:
              {{- toYaml .Values.cron.args | nindent 16 }}
