apiVersion: v1
kind: Secret
metadata:
  name: {{ include "AhedFinal.fullname" . }}
  labels:
    {{- include "AhedFinal.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.secret.SECRET_KEY | b64enc | quote }}
 